import type { Shop, MenuCategory, MenuItem, ModifierGroup, ModifierOption, ItemModifierLink, Order, OrderItem, OrderItemModifier } from '@/types'

export const demoShop: Shop = {
  id: '00000000-0000-0000-0000-000000000001',
  slug: 'cafeteria-demo',
  name: 'Cafe de la Esquina',
  legal_name: 'Cafe de la Esquina SA de CV',
  timezone: 'America/Mexico_City',
  currency: 'MXN',
  locale: 'es',
  tax_included: true,
  tax_rate: 0,
  address: 'Calle Durango 123, Roma Norte, CDMX',
  lat: 19.4194,
  lng: -99.1656,
  logo_url: null,
  brand_color: '#C45D3A',
  stripe_account_id: null,
  stripe_connect_status: 'pending',
  owner_id: null,
  status: 'active',
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
}

export const demoCategories: MenuCategory[] = [
  { id: 'cat-1', shop_id: demoShop.id, name: 'Bebidas calientes', sort_order: 1, is_active: true, created_at: '' },
  { id: 'cat-2', shop_id: demoShop.id, name: 'Bebidas frias', sort_order: 2, is_active: true, created_at: '' },
  { id: 'cat-3', shop_id: demoShop.id, name: 'Panaderia', sort_order: 3, is_active: true, created_at: '' },
]

export const demoModifierGroups: ModifierGroup[] = [
  { id: 'mg-1', shop_id: demoShop.id, name: 'Leche', min_select: 0, max_select: 1, sort_order: 1, created_at: '' },
  { id: 'mg-2', shop_id: demoShop.id, name: 'Tamano', min_select: 1, max_select: 1, sort_order: 2, created_at: '' },
]

export const demoModifierOptions: ModifierOption[] = [
  { id: 'mo-1', group_id: 'mg-1', name: 'Entera', price_cents: 0, is_active: true, sort_order: 1, created_at: '' },
  { id: 'mo-2', group_id: 'mg-1', name: 'Deslactosada', price_cents: 500, is_active: true, sort_order: 2, created_at: '' },
  { id: 'mo-3', group_id: 'mg-1', name: 'Almendra', price_cents: 1500, is_active: true, sort_order: 3, created_at: '' },
  { id: 'mo-4', group_id: 'mg-2', name: 'Chico', price_cents: 0, is_active: true, sort_order: 1, created_at: '' },
  { id: 'mo-5', group_id: 'mg-2', name: 'Mediano', price_cents: 1000, is_active: true, sort_order: 2, created_at: '' },
  { id: 'mo-6', group_id: 'mg-2', name: 'Grande', price_cents: 2000, is_active: true, sort_order: 3, created_at: '' },
]

export const demoItemModifierLinks: ItemModifierLink[] = [
  { id: 'iml-1', item_id: 'item-1', group_id: 'mg-1', is_required: false, created_at: '' },
  { id: 'iml-2', item_id: 'item-1', group_id: 'mg-2', is_required: true, created_at: '' },
  { id: 'iml-3', item_id: 'item-2', group_id: 'mg-2', is_required: true, created_at: '' },
  { id: 'iml-4', item_id: 'item-4', group_id: 'mg-2', is_required: true, created_at: '' },
]

export const demoItems: MenuItem[] = [
  {
    id: 'item-1',
    shop_id: demoShop.id,
    category_id: 'cat-1',
    name: 'Cappuccino',
    description: 'Espresso doble con leche vaporizada y espuma cremosa.',
    price_cents: 5500,
    image_url: 'https://images.unsplash.com/photo-1572442388796-11668a67e53d?w=600&auto=format&fit=crop',
    is_active: true,
    is_86ed: false,
    prep_time_min: 4,
    sort_order: 1,
    created_at: '',
    updated_at: '',
  },
  {
    id: 'item-2',
    shop_id: demoShop.id,
    category_id: 'cat-1',
    name: 'Latte Vainilla',
    description: 'Cafe suave con leche caliente y un toque de vainilla.',
    price_cents: 6200,
    image_url: 'https://images.unsplash.com/photo-1461023058943-48dbf1399192?w=600&auto=format&fit=crop',
    is_active: true,
    is_86ed: false,
    prep_time_min: 4,
    sort_order: 2,
    created_at: '',
    updated_at: '',
  },
  {
    id: 'item-3',
    shop_id: demoShop.id,
    category_id: 'cat-1',
    name: 'Americano',
    description: 'Espresso con agua caliente, intenso y ligero.',
    price_cents: 4200,
    image_url: null,
    is_active: true,
    is_86ed: false,
    prep_time_min: 3,
    sort_order: 3,
    created_at: '',
    updated_at: '',
  },
  {
    id: 'item-4',
    shop_id: demoShop.id,
    category_id: 'cat-2',
    name: 'Cold Brew',
    description: 'Cafe infusionado en frio por 18 horas. Suave y refrescante.',
    price_cents: 6800,
    image_url: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?w=600&auto=format&fit=crop',
    is_active: true,
    is_86ed: false,
    prep_time_min: 2,
    sort_order: 1,
    created_at: '',
    updated_at: '',
  },
  {
    id: 'item-5',
    shop_id: demoShop.id,
    category_id: 'cat-2',
    name: 'Frappe Mocha',
    description: 'Cafe, hielo, chocolate y crema batida.',
    price_cents: 7500,
    image_url: 'https://images.unsplash.com/photo-1577968897966-3d4325b36b61?w=600&auto=format&fit=crop',
    is_active: true,
    is_86ed: false,
    prep_time_min: 5,
    sort_order: 2,
    created_at: '',
    updated_at: '',
  },
  {
    id: 'item-6',
    shop_id: demoShop.id,
    category_id: 'cat-3',
    name: 'Croissant de Mantequilla',
    description: 'Hojaldre dorado y crujiente, horneado diario.',
    price_cents: 4800,
    image_url: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=600&auto=format&fit=crop',
    is_active: true,
    is_86ed: false,
    prep_time_min: 1,
    sort_order: 1,
    created_at: '',
    updated_at: '',
  },
  {
    id: 'item-7',
    shop_id: demoShop.id,
    category_id: 'cat-3',
    name: 'Muffin de Arandanos',
    description: 'Esponjoso con arandanos frescos y un toque de limon.',
    price_cents: 5200,
    image_url: null,
    is_active: true,
    is_86ed: false,
    prep_time_min: 1,
    sort_order: 2,
    created_at: '',
    updated_at: '',
  },
]

export const demoOrders: (Order & { items: (OrderItem & { modifiers: OrderItemModifier[] })[] })[] = [
  {
    id: 'order-1',
    shop_id: demoShop.id,
    customer_id: null,
    status: 'received',
    payment_status: 'succeeded',
    subtotal_cents: 12700,
    tax_cents: 0,
    tip_cents: 0,
    total_cents: 12700,
    currency: 'MXN',
    pickup_type: 'asap',
    pickup_slot_id: null,
    pickup_time: null,
    customer_name: 'Maria Gonzalez',
    customer_phone: '+52 55 1234 5678',
    special_instructions: 'Leche de almendra y menos hielo.',
    created_at: new Date(Date.now() - 2 * 60000).toISOString(),
    updated_at: new Date().toISOString(),
    items: [
      {
        id: 'oi-1',
        order_id: 'order-1',
        item_id: 'item-1',
        item_name_snapshot: 'Cappuccino',
        unit_price_cents: 7000,
        quantity: 1,
        subtotal_cents: 7000,
        modifiers: [
          { id: 'oim-1', order_item_id: 'oi-1', option_id: 'mo-3', option_name_snapshot: 'Almendra', price_cents: 1500 },
          { id: 'oim-2', order_item_id: 'oi-1', option_id: 'mo-6', option_name_snapshot: 'Grande', price_cents: 2000 },
        ],
      },
      {
        id: 'oi-2',
        order_id: 'order-1',
        item_id: 'item-6',
        item_name_snapshot: 'Croissant de Mantequilla',
        unit_price_cents: 4800,
        quantity: 1,
        subtotal_cents: 4800,
        modifiers: [],
      },
    ],
  },
  {
    id: 'order-2',
    shop_id: demoShop.id,
    customer_id: null,
    status: 'preparing',
    payment_status: 'succeeded',
    subtotal_cents: 7500,
    tax_cents: 0,
    tip_cents: 0,
    total_cents: 7500,
    currency: 'MXN',
    pickup_type: 'asap',
    pickup_slot_id: null,
    pickup_time: null,
    customer_name: 'Carlos Ruiz',
    customer_phone: '+52 55 9876 5432',
    special_instructions: null,
    created_at: new Date(Date.now() - 8 * 60000).toISOString(),
    updated_at: new Date().toISOString(),
    items: [
      {
        id: 'oi-3',
        order_id: 'order-2',
        item_id: 'item-5',
        item_name_snapshot: 'Frappe Mocha',
        unit_price_cents: 7500,
        quantity: 1,
        subtotal_cents: 7500,
        modifiers: [{ id: 'oim-3', order_item_id: 'oi-3', option_id: 'mo-5', option_name_snapshot: 'Mediano', price_cents: 1000 }],
      },
    ],
  },
  {
    id: 'order-3',
    shop_id: demoShop.id,
    customer_id: null,
    status: 'ready',
    payment_status: 'succeeded',
    subtotal_cents: 12400,
    tax_cents: 0,
    tip_cents: 0,
    total_cents: 12400,
    currency: 'MXN',
    pickup_type: 'asap',
    pickup_slot_id: null,
    pickup_time: null,
    customer_name: 'Ana Torres',
    customer_phone: '+52 55 4567 8901',
    special_instructions: null,
    created_at: new Date(Date.now() - 15 * 60000).toISOString(),
    updated_at: new Date().toISOString(),
    items: [
      {
        id: 'oi-4',
        order_id: 'order-3',
        item_id: 'item-2',
        item_name_snapshot: 'Latte Vainilla',
        unit_price_cents: 6200,
        quantity: 2,
        subtotal_cents: 12400,
        modifiers: [],
      },
    ],
  },
]
