default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("DATABASE_HOST") { "localhost" } %>
  port: <%= ENV.fetch("DATABASE_PORT") { 5432 } %>
  username: <%= ENV.fetch("DATABASE_USERNAME") { "codespace" } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { "" } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: solocafe_development

test:
  <<: *default
  database: solocafe_test

production:
  <<: *default
  database: solocafe_production
  url: <%= ENV["DATABASE_URL"] %>
