source "https://rubygems.org"

gem "rails", "~> 8.1.4"
gem "pg", "~> 1.1"
gem "puma", ">= 5.0"

gem "bcrypt", "~> 3.1.7"
gem "jwt", "~> 2.9"
gem "stripe", "~> 13.0"
gem "redis", "~> 5.0"
gem "sidekiq", "~> 7.0"
gem "rack-cors"
gem "jbuilder", "~> 2.0"

gem "bootsnap", require: false
gem "tzinfo-data", platforms: %i[ windows jruby ]
gem "kamal", require: false
gem "thruster", require: false

group :development, :test do
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"
  gem "bundler-audit", require: false
  gem "brakeman", require: false
  gem "rubocop-rails-omakase", require: false
  gem "factory_bot_rails"
  gem "faker"
end

group :test do
  gem "minitest-spec-rails"
end
